### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [justindarc/openspin#1]
Greetings, 

I'm a graphic designer and I would be more than happy to contribute to your project by creating a logo for it, let me know if you are interested.

Best regards.

**Comment by justindarc** [comment]
@michaelizer yes please! That would be great! What sorta ideas did you have in mind?

**Comment by michaelizer** [comment]
I'd like to ask some questions before starting, your answers will help me to deliver a better product.

    What's the name that should be displayed on the logo?, If there should be any.
    How would you describe this project and What is it intended to do?
    What would you like this logo to transmit?

I'll look forward to your reply, kind regards.

**Comment by justindarc** [comment]
Well, this app is basically an open-source clone of HyperSpin: http://hyperspin-fe.com/

**Comment by michaelizer** [comment]
I'm working on something already

**Comment by michaelizer** [comment]
So so sorry for the delay, I want your opinion on these sketches
![imagen](https://user-images.githubusercontent.com/35619342/42343516-4e571e88-8067-11e8-87ea-0507f31992b3.png)

**Comment by justindarc** [comment]
Very cool! I think I like the color combo of the one on the bottom-left the best.

**Comment by michaelizer** [comment]
Awesome! I'll upload the files on a pull request, and also create a Google drive folder for the vector files and monochromatic versions.

**Comment by michaelizer** [comment]
Done ([#2](https://github.com/justindarc/openspin/pull/2). It was my pleasure, enjoy! :DD

**Comment by justindarc** [comment]
This looks so good. Thanks again for all your hard work!
